<?php

$navLinks = [
    [
        'name' => '吃瓜爆料',
        'links' => [
            ['name' => '黑料不打烊', 'url' => 'https://cgbdy16.com/'],
            ['name' => '911爆料网', 'url' => 'https://hljcg14.com'],
            ['name' => '91吃瓜', 'url' => 'https://jycg01.com'],
            ['name' => '吃瓜网', 'url' => 'https://cgwang11.com'],
            ['name' => '51黑料', 'url' => 'https://51wyhl06.com'],
            ['name' => 'A姐分享', 'url' => 'https://www.ahhhhfs.com'],
            ['name' => '黑料网', 'url' => 'https://hlwn25.com'],
            ['name' => '91爆料', 'url' => 'https://91bl2.com'],
            ['name' => '51暗网', 'url' => 'https://51aw22.com'],
            ['name' => '91大赛', 'url' => 'https://91ds14.com'],
            ['name' => '51吃瓜', 'url' => 'https://51cgy6.com/'],
            ['name' => '17吃瓜', 'url' => 'https://icg23.com'],
            ['name' => '51大赛', 'url' => 'https://51dsw11.com'],
            ['name' => '51爆料', 'url' => 'https://51blw12.com'],
            ['name' => '今日看料', 'url' => 'https://kanliao14.net'],
            ['name' => '91视频', 'url' => 'https://91sp26.com'],
            ['name' => '每日大乱斗', 'url' => 'https://idld7.com'],
            ['name' => '每日大赛', 'url' => 'https://mrdsw9.com']
        ]
    ],
    [
        'name' => '机场推荐',
        'links' => [
            ['name' => '一元机场', 'url' => 'https://www.xn--6nq44r2uh9rhj7f.com/#/register?code=PRJSlq2p']
        ]
    ],
    [
        'name' => '成人小说',
        'links' => [
            ['name' => '成人小说网', 'url' => 'https://crxs.me'],
            ['name' => '中文成人文学网', 'url' => 'https://xbookcn.org'],
            ['name' => '杏吧', 'url' => 'https://13219.gbypveea.xyz'],
            ['name' => '風月文學網', 'url' => 'https://h528.com'],
            ['name' => '69 成人小說網', 'url' => 'https://69story.com'],
            ['name' => '都市生活成人文學', 'url' => 'https://youbook.icu'],
            ['name' => '私语电台', 'url' => 'https://zhi77.xyz'],
            ['name' => '大碗宽面小说网', 'url' => 'https://dwkm.xyz'],
            ['name' => '情色小說網', 'url' => 'https://book18.org'],
            ['name' => 'TXTXI.com', 'url' => 'https://txtxi.com'],
            ['name' => '艾利浩斯学院图书馆', 'url' => 'https://alhs.live'],
            ['name' => '色文网', 'url' => 'https://m.senwen9.cc'],
            ['name' => '中文成人文學網', 'url' => 'https://xbookcn.com'],
            ['name' => '色情001', 'url' => 'https://seqing001.com'],
            ['name' => '杏色', 'url' => 'https://xx-book.com'],
            ['name' => '疯情书库', 'url' => 'https://aabook.xyz'],
            ['name' => 'X6成人文学網', 'url' => 'https://x6wx.com']
        ]
    ],
    [
        'name' => '日本AV',
        'links' => [
            ['name' => 'DSYSAV', 'url' => 'https://dsysav.com/'],
            ['name' => 'njav.tv', 'url' => 'https://njav.tv'],
            ['name' => 'JAVDAY.TV', 'url' => 'https://javday.tv'],
            ['name' => 'MissAV', 'url' => 'https://missav.com'],
            ['name' => 'JAV目錄大全', 'url' => 'https://javmenu.com'],
            ['name' => '正妹AV', 'url' => 'https://goodav17.com'],
            ['name' => 'Netflav', 'url' => 'https://netflav.com'],
            ['name' => 'JAVHD', 'url' => 'https://javhd.com'],
            ['name' => 'PornBest', 'url' => 'https://pornbest.org'],
            ['name' => 'JavDB', 'url' => 'https://javdb.live'],
            ['name' => 'ThisAV.com', 'url' => 'https://thisav.com'],
            ['name' => 'SexTB.net', 'url' => 'https://sextb.net'],
            ['name' => 'AV01.tv', 'url' => 'https://av01.tv'],
            ['name' => 'GGJAV', 'url' => 'https://ggjav.com'],
            ['name' => 'jav777', 'url' => 'https://jav777.xyz'],
            ['name' => '水果派AV解说', 'url' => 'https://tk5.app'],
            ['name' => 'JAVHD.icu', 'url' => 'https://javhd.icu'],
            ['name' => 'Watch JAV Online', 'url' => 'https://watchjavonline.com'],
            ['name' => 'Javseen', 'url' => 'https://javseen.tv'],
            ['name' => 'Youavhub', 'url' => 'https://youavhub.com'],
            ['name' => 'Javbar.com', 'url' => 'https://javbar.com'],
            ['name' => 'JAVFINDER', 'url' => 'https://javfinder.ai'],
            ['name' => 'HighPorn', 'url' => 'https://highporn.net'],
            ['name' => 'JavDoe', 'url' => 'https://javdoe.to'],
            ['name' => 'Jav Guru', 'url' => 'https://jav.guru']
        ]
    ],
    [
        'name' => '欧美视频',
        'links' => [
            ['name' => 'xvideos镜像', 'url' => 'https://xvtz.pages.dev'],
            ['name' => 'PornHub', 'url' => 'https://cn.pornhub.com'],
            ['name' => 'XVideos', 'url' => 'https://www.xvideos.com'],
            ['name' => 'PussySpace', 'url' => 'https://www.pussyspace.com/'],
            ['name' => 'OK.XXX', 'url' => 'https://ok.xxx'],
            ['name' => 'HotMovs', 'url' => 'https://hotmovs.com'],
            ['name' => 'Upornia', 'url' => 'https://upornia.com'],
            ['name' => 'PornHoarder', 'url' => 'https://pornhoarder.tv'],
            ['name' => 'Nuvid', 'url' => 'https://www.nuvid.com'],
            ['name' => 'Sexu', 'url' => 'https://sexu.com'],
            ['name' => 'HqPorner', 'url' => 'https://hqporner.com'],
            ['name' => 'RedWap XXX', 'url' => 'https://redwap-xxx.com'],
            ['name' => 'PornTrex', 'url' => 'https://www.porntrex.com'],
            ['name' => 'SunPorno', 'url' => 'https://www.sunporno.com'],
            ['name' => 'Xozilla', 'url' => 'https://www.xozilla.com'],
            ['name' => 'BabesTube', 'url' => 'https://www.babestube.com'],
            ['name' => 'AlotPorn', 'url' => 'https://www.alotporn.com'],
            ['name' => 'XFreeHD', 'url' => 'https://www.xfreehd.com'],
            ['name' => 'HD Sex', 'url' => 'https://hdsex.org'],
            ['name' => 'ThisVid', 'url' => 'https://thisvid.com'],
            ['name' => 'VikiPorn', 'url' => 'https://www.vikiporn.com'],
            ['name' => 'XNXX', 'url' => 'http://www.xnxx.com'],
            ['name' => 'Pornwhite', 'url' => 'https://www.pornwhite.com'],
            ['name' => 'EMPFlix', 'url' => 'https://www.empflix.com'],
            ['name' => 'Faapy', 'url' => 'https://faapy.com'],
            ['name' => 'Kompoz', 'url' => 'https://kompoz2.com'],
            ['name' => 'PornVe', 'url' => 'https://pornve.com'],
            ['name' => 'PornHat', 'url' => 'https://www.pornhat.com'],
            ['name' => 'XGROOVY', 'url' => 'https://cn.xgroovy.com'],
            ['name' => 'Sex', 'url' => 'https://www.sex.com'],
            ['name' => 'AnyPorn', 'url' => 'https://anyporn.com'],
            ['name' => 'Eporner', 'url' => 'https://www.eporner.com'],
            ['name' => 'SexVid', 'url' => 'https://sexvid.ws'],
            ['name' => 'xHamster', 'url' => 'https://zh.xhamster.com'],
            ['name' => 'Beeg', 'url' => 'https://beeg.com'],
            ['name' => 'SpankBang', 'url' => 'https://spankbang.com'],
            ['name' => 'YouJizz', 'url' => 'https://www.youjizz.com'],
            ['name' => 'PornHD', 'url' => 'https://www.pornhd.com'],
            ['name' => '4Tube', 'url' => 'https://www.4tube.com'],
            ['name' => 'YouPorn', 'url' => 'https://www.youporn.com'],
            ['name' => 'PornOne', 'url' => 'https://pornone.com'],
            ['name' => 'Redtube', 'url' => 'https://www.redtube.com'],
            ['name' => 'GotPorn', 'url' => 'https://www.gotporn.com'],
            ['name' => '3Movs', 'url' => 'https://www.3movs.com'],
            ['name' => 'Tube8', 'url' => 'https://www.tube8.com'],
            ['name' => 'Motherless', 'url' => 'https://motherless.com'],
            ['name' => 'PornDig', 'url' => 'https://www.porndig.com'],
            ['name' => 'PornTube', 'url' => 'https://www.porntube.com'],
            ['name' => 'Cumlouder', 'url' => 'https://www.cumlouder.com'],
            ['name' => 'Txxx', 'url' => 'https://txxx.com'],
            ['name' => 'PornDoe', 'url' => 'https://porndoe.com'],
            ['name' => 'TNAFlix', 'url' => 'https://www.tnaflix.com'],
            ['name' => 'Thumbzilla', 'url' => 'https://www.thumbzilla.com'],
            ['name' => 'AnySex', 'url' => 'https://anysex.com'],
            ['name' => 'DrTuber', 'url' => 'https://www.drtuber.com'],
            ['name' => 'Porn300', 'url' => 'https://www.porn300.com'],
            ['name' => 'HD Zog', 'url' => 'https://hdzog.com']
        ]
    ],
    [
        'name' => '成人动漫',
        'links' => [
            ['name' => '猫漫客', 'url' => 'https://maomanke.com'],
            ['name' => '韩漫免费', 'url' => 'https://www.hanmanmianfei.com'],
            ['name' => '十八漫画', 'url' => 'https://sejieba.esefywbo.cc/?chan=sejieba'],
            ['name' => '18H汉化漫画', 'url' => 'https://7tn.top'],
            ['name' => '涩涩汉化漫画', 'url' => 'https://ss8.top'],
            ['name' => '逆次元逆ACG', 'url' => 'https://www.freeacg4.org'],
            ['name' => '连连看漫画', 'url' => 'https://www.hmllk.com'],
            ['name' => '末日動漫', 'url' => 'https://share.acgnx.se/'],
            ['name' => 'K漫画', 'url' => 'https://kmh005.com/home'],
            ['name' => '绅夜漫画', 'url' => 'https://syacomic03.site'],
            ['name' => '绅士仓库', 'url' => 'https://cangku.moe'],
            ['name' => '漫画车', 'url' => 'http://www.manhuache.com'],
            ['name' => '漫小肆', 'url' => 'https://www.mxs15.cc'],
            ['name' => '巴卡漫画', 'url' => 'https://baka1.my'],
            ['name' => 'Hanime1', 'url' => 'https://hanime1.me'],
            ['name' => '开心看漫画', 'url' => 'https://kxmanhua1.com'],
            ['name' => '饭团动漫', 'url' => 'https://ppoft.com'],
            ['name' => '顶点漫画', 'url' => 'https://www.apexmh.com'],
            ['name' => '摸摸漫画', 'url' => 'https://9smoc.fun'],
            ['name' => '鸟鸟韩漫', 'url' => 'https://nnhm6.xyz'],
            ['name' => '哔咔漫画', 'url' => 'https://pica.pipigou703.top/'],
            ['name' => 'HO5HO', 'url' => 'https://www.ho5ho.com'],
            ['name' => 'A漫', 'url' => 'https://aman7.org/'],
            ['name' => '必应漫画', 'url' => 'https://www.biyingmh.com'],
            ['name' => '小春光H漫', 'url' => 'https://www.xcg123.com'],
            ['name' => '哇嘎哒漫画', 'url' => 'https://www.wgada.com/'],
            ['name' => '禁漫天堂', 'url' => 'https://jm-uc.org/JBWYDX'],
            ['name' => '绅士の庭', 'url' => 'https://gmgard.moe'],
            ['name' => 'Hitomi', 'url' => 'https://hitomi.la'],
            ['name' => 'Rule34', 'url' => 'https://rule34.xxx/'],
            ['name' => 'Simply Hentai', 'url' => 'https://www.simply-hentai.com'],
            ['name' => '喜漫漫画', 'url' => 'https://favcomic.com?code=wKEAPXI'],
            ['name' => 'H-Comic', 'url' => 'https://h-comic.com/'],
            ['name' => 'aix论坛', 'url' => 'https://www.aixgame.xyz'],
            ['name' => '污污漫画', 'url' => 'https://www.55comics.com/'],
            ['name' => '松鼠症倉庫', 'url' => 'https://fw9xusavz7c.top'],
            ['name' => '南+', 'url' => 'https://www.south-plus.net'],
            ['name' => 'JieDm', 'url' => 'https://www.jiedm.com'],
            ['name' => '萌幻之乡', 'url' => 'https://www.mhh1.com'],
            ['name' => '萌次元', 'url' => 'https://nb.mcy002.org'],
            ['name' => '漫蛙漫画', 'url' => 'https://fuwt.cc/mw666'],
            ['name' => 'ACG糖漫画', 'url' => 'https://www.acgotang.com'],
            ['name' => '肉肉漫画', 'url' => 'https://18rouman.org'],
            ['name' => 'ACG漫画网', 'url' => 'https://acgmhb.com'],
            ['name' => 'Hentai2Read', 'url' => 'https://hentai2read.com'],
            ['name' => '2DFan', 'url' => 'https://2dfan.com'],
            ['name' => 'Nyahentai', 'url' => 'https://nyahentai.info'],
            ['name' => 'E-Hentai', 'url' => 'https://e-hentai.org'],
            ['name' => '拷贝漫画', 'url' => 'https://www.mangacopy.com'],
            ['name' => '琉璃神社', 'url' => 'https://www.hacg.icu'],
            ['name' => '177漫画', 'url' => 'https://www.177picyy.com'],
            ['name' => 'エロ漫画コング', 'url' => 'https://eromanga-kong.com/web/'],
            ['name' => '精品区', 'url' => 'https://www.jpq.me'],
            ['name' => '风花雪月', 'url' => 'https://fhxy-c.top'],
            ['name' => '香香腐宅', 'url' => 'https://fuhouse.club/NMnSDC'],
            ['name' => 'nHentai', 'url' => 'https://nhentai.net'],
            ['name' => '漫画DB', 'url' => 'https://www.manhuadb.com'],
            ['name' => '哔咔庇护所v2', 'url' => 'https://ios.pipigou703.top/'],
            ['name' => '肉漫屋', 'url' => 'https://roum20.xyz/home'],
            ['name' => 'B次元', 'url' => 'https://bbacgn.bio/'],
            ['name' => '龙禁漫', 'url' => 'https://52longjm.com'],
            ['name' => '爱看漫画', 'url' => 'https://ikanmanhua.org'],
            ['name' => '紳士漫畫', 'url' => 'https://www.wnacg01.cc/'],
            ['name' => 'NiceCat', 'url' => 'https://web.nicecat.cc'],
            ['name' => '灵梦御所', 'url' => 'https://blog.reimu.net'],
            ['name' => '宅宅爱动漫', 'url' => 'https://18h.animezilla.com'],
            ['name' => 'H次元', 'url' => 'https://h-ciyuan.com'],
            ['name' => '韩国A漫', 'url' => 'https://www.hanguoaman.com']
        ]
    ],
    [
        'name' => '特色好站',
        'links' => [
            ['name' => '91福利社', 'url' => 'https://modelfun666.com'],
            ['name' => '快乐堂', 'url' => 'https://www.happyporn7.com'],
            ['name' => '心灵社区', 'url' => 'https://www.xlsq19.com'],
            ['name' => 'DL资源', 'url' => 'https://dl1010.com'],
            ['name' => '91Torture', 'url' => 'https://91torture.com/'],
            ['name' => 'OnlyFans资源社', 'url' => 'https://of996.com'],
            ['name' => 'Sp小馆', 'url' => 'https://sp-fans.com'],
            ['name' => 'iBoy1069', 'url' => 'https://iboy1069.com'],
            ['name' => '原味阁', 'url' => 'https://www.52ywg.info'],
            ['name' => '青兰花', 'url' => 'https://www.qinglanhua2025.com/'],
            ['name' => '街射网', 'url' => 'https://99jse.com'],
            ['name' => '双马尾女孩', 'url' => 'http://twintail-japan.com'],
            ['name' => 'BDSMTV', 'url' => 'https://bdsmtvsh0wa.com/'],
            ['name' => 'ASMR Online', 'url' => 'https://asmr-300.com/'],
            ['name' => '电影裸体片段', 'url' => 'https://searchcelebrityhd.com'],
            ['name' => '我爱原味阁', 'url' => 'https://www.52yuanweige.net'],
            ['name' => 'Feet 9', 'url' => 'https://www.feet9.com'],
            ['name' => '明星精彩片段', 'url' => 'https://videocelebs.net'],
            ['name' => '绳虐网', 'url' => 'https://shengnue123.com'],
            ['name' => '爱程sp社区', 'url' => 'https://www.nowspank.com'],
            ['name' => '品丝恋足', 'url' => 'http://pinsilianzu8.com'],
            ['name' => '直播录屏', 'url' => 'https://lupinglaikan.top'],
            ['name' => 'SM调教室', 'url' => 'https://45.151.135.170'],
            ['name' => '阴茎锻炼手册', 'url' => 'https://jiba.plus'],
            ['name' => '绳艺束缚网', 'url' => 'https://shengyishufu.com'],
            ['name' => '原味窝', 'url' => 'https://maomiyuanwei.com'],
            ['name' => 'ASMR基佬中心', 'url' => 'https://asmr.uno/'],
            ['name' => '妖狐吧', 'url' => 'https://www.smlsy.com'],
            ['name' => '娘娘腔', 'url' => 'https://iamsissy.com/zh-CN'],
            ['name' => '绳艺情', 'url' => 'https://www.shengyiqing.com/'],
            ['name' => '我爱原味网', 'url' => 'https://www.52yuanwei43.com/'],
            ['name' => '女主天地', 'url' => 'https://www.nztd54.com'],
            ['name' => '女性の美脚', 'url' => 'https://legs.a-hadaka.jp'],
            ['name' => '黎家大院', 'url' => 'https://ljdy.cc'],
            ['name' => '绳艺园', 'url' => 'https://gallery.sykb169.org'],
            ['name' => '爱足视频', 'url' => 'http://a383583.aizu10.xyz'],
            ['name' => '男娘大学', 'url' => 'https://sissy.game/usr/college/index.html'],
            ['name' => '私密味道', 'url' => 'https://simiweidao1.com'],
            ['name' => '蕾丝猫', 'url' => 'https://www.lesmao.co'],
            ['name' => '大奶视频', 'url' => 'https://bigboobbettys.com'],
            ['name' => '内衣秀', 'url' => 'https://aliphotos.ru'],
            ['name' => '斯慕视频网', 'url' => 'https://ism409.com/'],
            ['name' => '肛交视频', 'url' => 'https://www.assoass.com'],
            ['name' => 'BDSM调教', 'url' => 'https://bdsmstreak.com'],
            ['name' => 'Tube BDSM', 'url' => 'https://www.tubebdsm.com'],
            ['name' => '绳瘾', 'url' => 'https://www.vid419.com'],
            ['name' => '明星那些事', 'url' => 'https://file.uhsea.com/2407/4c17da4697cd8ded0860f200889eecb7Z8.pdf'],
            ['name' => '爱绑网', 'url' => 'https://www.woaikunbang.com'],
            ['name' => '惩罚者', 'url' => 'https://www.punishbang.com'],
            ['name' => 'OK原味圈', 'url' => 'https://ywywywyw.cn']
        ]
    ],
    [
        'name' => '美图写真',
        'links' => [
            ['name' => '迷人网', 'url' => 'https://mirenwang.com'],
            ['name' => '69图社', 'url' => 'https://fuli13.shop/123/456/'],
            ['name' => '51脱衣图社', 'url' => 'https://fuli19.shop/123/456/'],
            ['name' => '社福利姬', 'url' => 'https://www.prsfl.xyz'],
            ['name' => '草莓图库', 'url' => 'https://meimei444.cfd'],
            ['name' => '呦呦图库', 'url' => 'https://fuli15.shop/123/456/'],
            ['name' => 'XO福利图', 'url' => 'https://kb1.a10xofulitu.com/儿歌三百首/'],
            ['name' => '山相图社', 'url' => 'https://fuli14.shop/123/123/'],
            ['name' => '美图乐', 'url' => 'https://www.meitule.net'],
            ['name' => '91美图', 'url' => 'https://91mt.cc'],
            ['name' => '柠檬皮', 'url' => 'https://www.emonl.com'],
            ['name' => '呦糖社', 'url' => 'https://www.nicesss.com'],
            ['name' => '微密猫', 'url' => 'https://wemecat.vip'],
            ['name' => '妹子吧', 'url' => 'https://meiziba.cc/'],
            ['name' => '成人貼圖', 'url' => 'https://www.sexphotos.cc'],
            ['name' => 'Everia', 'url' => 'https://everia.club'],
            ['name' => '每日妹子图', 'url' => 'https://meizi2.com/'],
            ['name' => 'Jablehk', 'url' => 'https://jablehk.com'],
            ['name' => '国模网', 'url' => 'https://gm67.xyz'],
            ['name' => '提姆正妹', 'url' => 'http://www.timliao.com/bbs/forumdisplay.php?fid=18'],
            ['name' => '街拍猫', 'url' => 'https://www.jiepaim.com/index3.php'],
            ['name' => '成人贴图', 'url' => 'https://adultspic.com'],
            ['name' => '4KUP', 'url' => 'https://4kup.net'],
            ['name' => '美美百秀', 'url' => 'https://www.mmbx24.cc'],
            ['name' => '热丝美图', 'url' => 'https://mt.20rs.com'],
            ['name' => '魔镜原创摄影', 'url' => 'https://www.520mojing.com'],
            ['name' => '启明星摄影', 'url' => 'http://www.qmxyc.com'],
            ['name' => '美之图', 'url' => 'https://kkmzt.com'],
            ['name' => '青年美圖', 'url' => 'https://jrants.com/'],
            ['name' => '很牛帮', 'url' => 'https://hnbang.com'],
            ['name' => '赞MM', 'url' => 'https://www.zanmm.com'],
            ['name' => '名腿网', 'url' => 'https://www.mingtuiw.com/'],
            ['name' => '4KHD', 'url' => 'https://juzpz.cchh.ink'],
            ['name' => 'MissKon', 'url' => 'https://misskon.com'],
            ['name' => 'Simply-Cosplay', 'url' => 'https://www.simply-cosplay.com'],
            ['name' => '后宫网', 'url' => 'https://www.hougon.me/'],
            ['name' => 'エロ画像', 'url' => 'https://onapple.jp'],
            ['name' => 'Cos4K', 'url' => 'https://cos4k.com'],
            ['name' => '爱变色', 'url' => 'https://aibianse.github.io'],
            ['name' => 'Artgravia', 'url' => 'https://www.artgravia.com'],
            ['name' => '绅士会所', 'url' => 'https://www.90987086.xyz'],
            ['name' => '抖你妹', 'url' => 'https://dounimei.akmn.top'],
            ['name' => '爱看INS', 'url' => 'https://www.ikanins.com'],
            ['name' => '街拍小站', 'url' => 'https://www.jp91.com'],
            ['name' => '美图录', 'url' => 'https://meitulu.me'],
            ['name' => '街拍大师', 'url' => 'https://www.jiepaids.com'],
            ['name' => '真实街拍', 'url' => 'https://mt3009.net'],
            ['name' => '桃花社', 'url' => 'https://www.iiblog.live'],
            ['name' => 'PornPics', 'url' => 'https://www.pornpics.com/zh/'],
            ['name' => 'Hitxhot', 'url' => 'https://hitxhot.com'],
            ['name' => '性感尤物', 'url' => 'http://www.xgyouwu.com'],
            ['name' => 'JN美眉网', 'url' => 'https://www.jnmmw.com'],
            ['name' => 'CosBlay', 'url' => 'https://cosblay.com'],
            ['name' => '微图坊', 'url' => 'https://www.v2ph.com'],
            ['name' => '秀色女神', 'url' => 'https://www.xsnvshen.co'],
            ['name' => '六色网', 'url' => 'https://www.06se.com'],
            ['name' => 'JJPicc', 'url' => 'https://www.jjpicss.com'],
            ['name' => '丝域', 'url' => 'https://www.coheel.com'],
            ['name' => 'NongMo', 'url' => 'https://ilovexs.com']
        ]
    ],
    [
        'name' => '美女直播',
        'links' => [
            ['name' => 'CamSoda', 'url' => 'https://www.camsoda.com'],
            ['name' => 'J-Live', 'url' => 'https://www.j-live.tv'],
            ['name' => 'JerkMate', 'url' => 'https://www.jerkmatelive.org'],
            ['name' => 'Riv Cams', 'url' => 'https://www.rivcams.com'],
            ['name' => 'Naked', 'url' => 'https://www.naked.com'],
            ['name' => 'Bonga', 'url' => 'https://bongacams.com'],
            ['name' => 'XloveCam', 'url' => 'https://www.xlovecam.com'],
            ['name' => 'Camster', 'url' => 'https://www.camster.com'],
            ['name' => 'Cams', 'url' => 'https://cams.com'],
            ['name' => 'CAM4', 'url' => 'https://cam4.com'],
            ['name' => 'gocams', 'url' => 'https://goxxxcams.com'],
            ['name' => 'Crush', 'url' => 'https://www.luckycrush.live'],
            ['name' => 'Chatur', 'url' => 'https://chaturbate.com'],
            ['name' => 'SexAsian', 'url' => 'https://www.livesexasian.com'],
            ['name' => 'Sakura', 'url' => 'https://www.sakuralive.com'],
            ['name' => 'SWAG', 'url' => 'https://swag.live'],
            ['name' => 'NudeLive', 'url' => 'https://nudelive.com'],
            ['name' => '六间房', 'url' => 'https://www.6.cn'],
            ['name' => 'YY', 'url' => 'https://www.yy.com'],
            ['name' => '奇秀', 'url' => 'https://x.pps.tv'],
            ['name' => '我秀网', 'url' => 'https://www.woxiu.com'],
            ['name' => 'TokyoPorn', 'url' => 'https://tokyoporn.com'],
            ['name' => 'Pussy', 'url' => 'https://www.pussy.com'],
            ['name' => '花椒直播', 'url' => 'https://www.huajiao.com'],
            ['name' => '聚星直播', 'url' => 'https://jx.kuwo.cn'],
            ['name' => 'FC2 Live', 'url' => 'https://live.fc2.com/adult'],
            ['name' => 'Voyeur House', 'url' => 'https://voyeur-house.tv'],
            ['name' => 'BIMBIM', 'url' => 'https://www.bimbim.com'],
            ['name' => 'LiveJasmin', 'url' => 'https://www.livejasmin.com'],
            ['name' => 'Flirtify', 'url' => 'https://flirtify.com'],
            ['name' => 'Tnaflix', 'url' => 'https://www.tnaflixcams.com'],
            ['name' => 'Bitcoin Cams', 'url' => 'https://bitcoincams.xxx'],
            ['name' => 'FootSeen', 'url' => 'https://www.footseen.xyz'],
            ['name' => '九秀直播', 'url' => 'https://www.9xiu.com']
        ]
    ],
    [
        'name' => '性息交友',
        'links' => [
            ['name' => '51品茶', 'url' => 'https://5cdba.krctjym.cc/?code=bayhv&c=14449'],
            ['name' => '木瓜社区', 'url' => 'https://99ppy.com/'],
            ['name' => '91性息港', 'url' => 'https://91xxg.com'],
            ['name' => '51同城约会', 'url' => 'https://c4.oou677.shop'],
            ['name' => '不夜城', 'url' => 'https://m1.52tea.xyz'],
            ['name' => '香凤楼', 'url' => 'https://www.xfl001.com'],
            ['name' => '91风流', 'url' => 'https://91fengliu.club'],
            ['name' => '91约炮', 'url' => 'https://91yue-pao.com'],
            ['name' => '91快活林', 'url' => 'https://91cmmb.com'],
            ['name' => '约炮吧', 'url' => 'https://ypb88.xyz/lailu/1'],
            ['name' => '凤楼馆', 'url' => 'https://q2.flg118.xyz'],
            ['name' => '91风流楼凤', 'url' => 'https://91cmmb.net'],
            ['name' => '约啪啪', 'url' => 'https://yue-papa.com'],
            ['name' => '快活林', 'url' => 'https://27eanbvoo.xyz/?u=wwO9TCqLWZct'],
            ['name' => '包养圈', 'url' => 'https://shequan1.com'],
            ['name' => '红蜻蜓社区', 'url' => 'https://hqt133.com'],
            ['name' => '妻社', 'url' => 'https://qishe.qisheggy2025.com/fanh5/?iuid=6399'],
            ['name' => '161香港楼凤', 'url' => 'http://www.161sex.com'],
            ['name' => '华同', 'url' => 'https://www.gaycn.top'],
            ['name' => '英伦客栈', 'url' => 'https://www.yinglunkezhan.com'],
            ['name' => '马来西亚性息', 'url' => 'https://188sex.com'],
            ['name' => '148香港楼凤', 'url' => 'https://www.miss148.com'],
            ['name' => '搜同', 'url' => 'https://www.stboy.net'],
            ['name' => '141-161楼凤', 'url' => 'https://141-161.com/zh/'],
            ['name' => '帅兔社区', 'url' => 'https://www.shuaito.buzz/?fromuid=1415611']
        ]
    ],
    [
        'name' => '成人游戏',
        'links' => [
            ['name' => 'H游戏大全', 'url' => 'https://h18-games.net'],
            ['name' => '邪萌天祭', 'url' => 'https://www.akumoe.cc'],
            ['name' => 'Comix Harem', 'url' => 'https://www.comixharem.com'],
            ['name' => '3D SexVilla', 'url' => 'https://www.3dsexvilla.com'],
            ['name' => '3DXChat', 'url' => 'https://3dxchat.com'],
            ['name' => '老司机游玩', 'url' => 'https://www.ahlsj.xyz'],
            ['name' => '工口.R18', 'url' => 'https://l.tyrantdb.com/OJ99pfiG'],
            ['name' => 'MNF Club', 'url' => 'https://www.mnfclub.com'],
            ['name' => 'Hentai Heroes', 'url' => 'https://www.hentaiheroes.com'],
            ['name' => 'EROLABS', 'url' => 'https://www.ero-labs.com'],
            ['name' => 'LifeSelector', 'url' => 'https://lifeselector.com/game/listGames'],
            ['name' => 'Cunt Wars', 'url' => 'https://cuntwars.com'],
            ['name' => 'Erogames', 'url' => 'https://erogames.com/zh'],
            ['name' => 'Nutaku', 'url' => 'https://www.nutaku.net/zh/'],
            ['name' => 'Yareel 3D', 'url' => 'https://yareel.com'],
            ['name' => 'Girlvanic', 'url' => 'https://www.girlvanic.com'],
            ['name' => 'SexEmulator', 'url' => 'https://www.sexemulator.com'],
            ['name' => 'Fap Titans', 'url' => 'https://faptitans.com'],
            ['name' => 'Hentai Clicker', 'url' => 'https://www.hentaiclicker.com'],
            ['name' => 'Big Bang Empire', 'url' => 'http://www.bigbangempire.com'],
            ['name' => 'Smutstone', 'url' => 'https://smutstone.com'],
            ['name' => 'RedLightCenter', 'url' => 'https://www.redlightcenter.com'],
            ['name' => 'H365', 'url' => 'https://www.365h.work'],
            ['name' => 'MeetFuckGames', 'url' => 'https://www.meetandfuckgames.com'],
            ['name' => 'SinVR', 'url' => 'https://sinvr.co'],
            ['name' => 'Studio FOW', 'url' => 'https://studiofow.com'],
            ['name' => 'Sex Gangsters', 'url' => 'https://www.sexgangsters.com'],
            ['name' => 'HotCandyLand', 'url' => 'https://hotcandyland.com'],
            ['name' => '黄油圈', 'url' => 'https://hcysj2.site']
        ]
    ],
    [
        'name' => 'AI色情',
        'links' => [
            ['name' => 'AI Porn', 'url' => 'https://ai-porn.ai'],
            ['name' => 'Pornify', 'url' => 'https://pornify.cc'],
            ['name' => '色情生成器', 'url' => 'https://aiexotic.com'],
            ['name' => 'AI 色情生成器', 'url' => 'https://dessi.io'],
            ['name' => 'Unstable Diffusion', 'url' => 'https://unstability.ai'],
            ['name' => 'SoulGen', 'url' => 'https://soulgen.ai'],
        ]
    ],
    [
        'name' => '片商官网',
        'links' => [
            ['name' => 'S-Cute', 'url' => 'https://s-cute.com'],
            ['name' => '一本道', 'url' => 'https://1pondo.tv'],
            ['name' => 'SOD', 'url' => 'https://sod.co.jp'],
            ['name' => '麻豆传媒映画', 'url' => 'https://madou02.com'],
            ['name' => 'X-Art', 'url' => 'https://x-art.com'],
            ['name' => '加勒比', 'url' => 'https://caribbeancom.com'],
            ['name' => '東京熱', 'url' => 'https://tokyo-hot.com'],
            ['name' => 'S1', 'url' => 'https://s1s1s1.com'],
            ['name' => '天美传媒影视', 'url' => 'https://timi1.me'],
            ['name' => '萝莉社', 'url' => 'https://lolis02.com'],
            ['name' => '爱豆传媒', 'url' => 'https://idol01.com'],
            ['name' => 'ModelTV', 'url' => 'https://modeltv.com'],
            ['name' => 'TWAV台色情趣', 'url' => 'https://twav.asia'],
            ['name' => '杏吧视频', 'url' => 'https://xbh5.info'],
            ['name' => 'mywife.cc', 'url' => 'https://mywife.cc'],
            ['name' => 'HEYZO', 'url' => 'https://heyzo.com'],
            ['name' => '91制片厂', 'url' => 'https://jmnkip.com'],
            ['name' => '香蕉视频', 'url' => 'https://xjxjxj27.cc']
        ]
    ],
    [
        'name' => '色情搜索',
        'links' => [
            ['name' => '色也', 'url' => 'https://seyeah.com'],
            ['name' => 'PornFind', 'url' => 'https://pornfind.org'],
            ['name' => 'NudeVista', 'url' => 'https://nudevista.com'],
            ['name' => 'FindTubes', 'url' => 'https://findtubes.com'],
            ['name' => 'Rexxx', 'url' => 'https://rexxx.com'],
            ['name' => 'PornMD', 'url' => 'https://pornmd.com'],
            ['name' => 'Noodlemagazine', 'url' => 'https://noodlemagazine.com']
        ]
    ],
    [
        'name' => '情色论坛',
        'links' => [
            ['name' => '草榴社區', 'url' => 'https://t66y.com'],
            ['name' => '色花堂', 'url' => 'https://sehuatang.org'],
            ['name' => '我愛78論壇', 'url' => 'https://5278.cc'],
            ['name' => '老王论坛', 'url' => 'https://laowang.vip'],
            ['name' => 'JKF 捷克論壇', 'url' => 'https://jkforum.net'],
            ['name' => '桃花族论坛', 'url' => 'https://thzc.cc'],
            ['name' => 'AV狼', 'url' => 'https://yylang.com'],
            ['name' => '色中色论坛', 'url' => 'https://sexinsex.net'],
            ['name' => '性吧', 'url' => 'https://sex8.cc'],
            ['name' => '洪爺', 'url' => 'https://bbs-tw.com'],
            ['name' => '第一会所', 'url' => 'https://sis001.com'],
            ['name' => '伊莉討論區', 'url' => 'https://eyny.com'],
            ['name' => '六九色堂', 'url' => 'https://hnu.mitang003.top'],
            ['name' => '酷18', 'url' => 'https://cool18.com'],
            ['name' => '南+ South Plus', 'url' => 'https://south-plus.org']
        ]
    ]
];